version: "3"

services:
  frontend:
    image: kennedyuche/vip-customer-web:v1
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    ports:
      - "3000:3000"

  volumes:
  node-modules:
